Revert "Clean import"
This reverts commit b9e5f424722002c16e26766c5cfb3c096a0a8240.

"ResolvedMap.java:56: error: Entry is not public in HashMap; cannot be accessed from outside package"