Weird explicit package name necessary for OpenJDK8 compiler:
   [javac]
/ifi/asgard/p00/envisage/srv/jenkins/jobs/J8-ABS-Bucky-Tests/workspace/frontend/gen/abs/frontend/ast/RepeatMap.java:83:
error: cannot find symbol
    [javac]         e.getAttribute().isRepeated |=
put(e.getKey(),e.getValue()) != null;

and

    [javac]
/ifi/asgard/p00/envisage/srv/jenkins/jobs/J8-ABS-Bucky-Tests/workspace/frontend/gen/abs/frontend/ast/Attribute.java:361:
error: incompatible types: abs.frontend.ast.Entry<String,BoundaryInt[]>
cannot be converted to java.util.Map.Entry<String,BoundaryInt[]>
    [javac]     collection.add(getIntFVarsHelp());