Also set casestudies.dir in ANT build, where most of the machinery was already in place. Add missing Choco-solver to runtime classpath because of:     [junit] Testcase: testFredhopper2 took 0.023 sec     [junit] 	Caused an ERROR     [junit] choco/kernel/model/variables/integer/IntegerExpressionVariable     [junit] java.lang.NoClassDefFoundError: choco/kernel/model/variables/integer/IntegerExpressionVariable     [junit] 	at abs.frontend.parser.ABSParser.invokeReduceAction(ABSParser.java:5529)
git-svn-id: https://repos.hats-project.eu:444/svn/hats/Tools/ABS/trunk@13614 97f52227-7fa9-4375-a72d-c1c733b1f48f